from blog_handler import BlogHandler
from main_page import MainPage
from welcome import Welcome
from post_page import PostPage
from new_post import NewPost
from blog_front import BlogFront
from edit_post import EditPost
from login import Login
from logout import Logout
from register import Register
from delete_post import DeletePost
